name: nbadfs
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - backcall=0.2.0
  - blas=1.0
  - ca-certificates=2020.6.24
  - certifi=2020.6.20
  - cycler=0.10.0
  - dbus=1.13.16
  - decorator=4.4.2
  - expat=2.2.9
  - fontconfig=2.13.0
  - freetype=2.10.2
  - glib=2.65.0
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - intel-openmp=2020.1
  - ipykernel=5.3.4
  - ipython=7.16.1
  - ipython_genutils=0.2.0
  - jedi=0.17.1
  - joblib=0.16.0
  - jpeg=9b
  - jupyter_client=6.1.6
  - jupyter_core=4.6.3
  - kiwisolver=1.2.0
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20191231
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libpng=1.6.37
  - libsodium=1.0.18
  - libstdcxx-ng=9.1.0
  - libuuid=1.0.3
  - libxcb=1.14
  - libxml2=2.9.10
  - matplotlib=3.2.2
  - matplotlib-base=3.2.2
  - mkl=2020.1
  - mkl-service=2.3.0
  - mkl_fft=1.1.0
  - mkl_random=1.1.1
  - ncurses=6.2
  - numpy=1.19.1
  - numpy-base=1.19.1
  - openssl=1.1.1g
  - pandas=1.1.0
  - parso=0.7.0
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=20.2.2
  - prompt-toolkit=3.0.5
  - ptyprocess=0.6.0
  - pygments=2.6.1
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - python=3.8.5
  - python-dateutil=2.8.1
  - pytz=2020.1
  - pyzmq=19.0.1
  - qt=5.9.7
  - readline=8.0
  - scikit-learn=0.23.1
  - scipy=1.5.0
  - seaborn=0.10.1
  - setuptools=49.6.0
  - sip=4.19.13
  - six=1.15.0
  - sqlite=3.32.3
  - threadpoolctl=2.1.0
  - tk=8.6.10
  - tornado=6.0.4
  - traitlets=4.3.3
  - wcwidth=0.2.5
  - wheel=0.34.2
  - xz=5.2.5
  - zeromq=4.3.2
  - zlib=1.2.11
  - pip:
      - amply==0.1.2
      - arrow==0.15.8
      - binaryornot==0.4.4
      - chardet==3.0.4
      - click==7.1.2
      - cookiecutter==1.7.2
      - dnspython==2.0.0
      - docutils==0.16
      - idna==2.10
      - jinja2==2.11.2
      - jinja2-time==0.2.0
      - markupsafe==1.1.1
      - ohmysportsfeedspy==2.1.0
      - poyo==0.5.0
      - pulp==2.3
      - pymongo==3.11.0
      - python-slugify==4.0.1
      - requests==2.24.0
      - simplejson==3.17.2
      - text-unidecode==1.3
      - tqdm==4.48.2
      - urllib3==1.25.10
      - xgboost==1.1.1
